name: deezer-lite-player
base: core22
version: '1.1.3'
summary: "Deezer Desktop App – High-Fidelity Music, Low CPU Usage"
description: |
  Optimized Electron-based Deezer client for Linux, focusing on high-fidelity audio,
  lower CPU consumption, and improved security.

grade: stable
confinement: strict  # Use 'devmode' during testing

apps:
  deezer-lite-player:
    command: electron .
    extensions: [gnome]
    plugs:
      - network
      - audio-playback
      - desktop
      - desktop-legacy
      - x11

parts:
  deezer:
    plugin: nil  # Use 'nil' since nodejs is not built-in
    source: .
    override-build: |
      sudo apt update
      sudo apt install -y nodejs npm
      npm install
    build-packages:
      - nodejs
      - npm
      - libx11-dev
      - libxkbfile-dev
      - libsecret-1-dev
      - libgtk-3-dev
      - libnss3
      - xvfb

