name: deezer-lite-player
base: core22           
version: '1.1.3'    
summary: "Deezer Desktop App – High-Fidelity Music, Low CPU Usage"
description: |
  Optimized Electron-based Deezer client for Linux, focusing on high-fidelity audio,
  lower CPU consumption, and improved security.
                                                           
grade: stable
confinement: strict  # Use 'devmode' during testing

apps:                                                                                                                                                                                                                                        
  deezer-lite-player:                                                                                                                                                                                                                        
    command: bin/electron .                                                                                                                                                                                                                  
    environment:                                                                                                                                                                                                                             
      ELECTRON_DISABLE_SECURITY_WARNINGS: 1
    extensions: [gnome]                                                                                               
    plugs:                                 
      - network            
      - audio-playback
      - desktop                            
      - desktop-legacy
      - x11             
      - unity7  # Adds better desktop integration  

parts:                                     
  deezer:                                                                                                             
    plugin: nil                            
    source: .              
    source-type: local  # Ensures Snapcraft copies all project files
    override-build: |                      
      set -xe  # Enables debugging output
                                                           
      # Update and install dependencies                    
      apt update                                           
      apt install -y curl                                                                                             
                                                           
      # Install Node.js 18 (LTS)                                                                                      
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -                                                       
      apt install -y nodejs                                                                                           
      npm install -g npm@10                                                                                           
                                                           
      # Verify installed Node.js version                   
      node -v                                         
      npm -v                                               
                                                           
      # Ensure we are in the correct directory             
      cd $SNAPCRAFT_PART_SRC                                                                                          
                                                                                                                      
      # Copy project files with rsync (avoids self-referencing errors)
      rsync -av --exclude=node_modules --exclude=snapcraft.yaml $SNAPCRAFT_PART_SRC/ $SNAPCRAFT_PART_BUILD/
                                                           
      # Change to the build directory and install dependencies
      cd $SNAPCRAFT_PART_BUILD
      npm install      
      npm install --save-dev electron electron-builder     
                                                           
      # Ensure Electron is copied to the snap
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin                 
      cp -r node_modules/electron $SNAPCRAFT_PART_INSTALL/bin/        
                                                                                                                      
    build-packages:                                                                                                   
      - curl                                                                                                          
      - rsync                                                                                                         
      - libx11-dev                                         
      - libxkbfile-dev                                     
      - libsecret-1-dev                                    
      - libgtk-3-dev                         
      - libnss3                                            
      - xvfb                                                                                                          

  desktop-integration:
    plugin: dump
    source: .
    organize:     
      deezer-lite-player.desktop: usr/share/applications/deezer-lite-player.desktop
    after: [deezer]    

